-d C:\Users\Basti\Documents\001-Master\SS26-FHW\Chip_Design\fpga\test\impl\gwsynthesis\test.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst C:\Users\Basti\Documents\001-Master\SS26-FHW\Chip_Design\fpga\test\src\physical_constraint.cst
-cfg C:\Users\Basti\Documents\001-Master\SS26-FHW\Chip_Design\fpga\test\impl\pnr\device.cfg
-sdc C:\Users\Basti\Documents\001-Master\SS26-FHW\Chip_Design\fpga\test\src\timing_constraints.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 25.000
-enable_dsrm 0
